language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t heeleeaz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true heeleeaz/docker-react npm run test